Hiscore list
thejpster/monotron-apps pull request #4
Opened 2018-10-20 20:31 UTC by icefoxen

Incorporates the other PR I made, and adds some more functionality.

Not yet sure if it works, since I don't have `arm-none-eabi-gcc` installed and can't even see if it compiles.  XD

2018-10-20 21:36 UTC, thejpster requested changes

2018-10-20 23:00 UTC, icefoxen commented on snake/main.c
> +    for (int i = 0; i < NUM_HISCORES; i++) {
Turns out you are entirely correct! I'll see if I can do this before the conference is over, I want to maybe be able to see it.

2018-10-21 03:51 UTC, icefoxen commented
I THINK that commit should do it; as I said, this is all untested.

2018-10-21 09:31 UTC, thejpster commented
So this suggests I need to write an emulator for Monotron using ggez to allow testing of Monotron apps on a PC ;)

Bonus points if it uses QEMU to execute Armv7em machine code rather than cross compiling!

2018-10-21 12:01 UTC, thejpster commented
I've pushed some changes to master you need to pick up. Once you have those, this builds, but crashes after the "GAME OVER" screen.

Sadly I've been unable to get GDB to debug things in RAM.

2018-10-21 21:50 UTC, thejpster commented
If you pull master, you can now test on Linux :)

2026-03-30 15:22 UTC, closed without merging